version: "4.2"
services:
  embassy-db:
    container_name: embassy-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: embassy-db
      stdin_open: true
      tty: true
    networks:
      - freecodecamp
networks:
  freecodecamp: