version: "4.2"
services:
  dev-db:
    container_name: embassy-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: embassy-db
    networks:
      - freecodecamp
networks:
  freecodecamp: